print(' ___________________________________________________________________')
print('| Welcome to the game:                                              |')
print('| This game is about you who awakes with no memorie of the past     |')
print('| You will encounter choices you have to make                       |')
print('| Choose wisely because you might end up dead                       |')
print('| Good luck...                                                      |')
print('|___________________________________________________________________|')
print('|                                                                   |')
print('| You awake in total darkness, you light a candle to see that you   |')
print('| are inside an arena.                                              |')
print('| Suddenly a huge door opens and a dragon comes out.                |')
print('| You see two potential weapons:                                    |')
print('| Option 1- A comically large spoon                                 |')
print('| Option 2- A backpack filled with paper airplanes strapped with    |')
print('| bombs                                                             |')
print(' ___________________________________________________________________')

